variables:
  CIBW_TEST_COMMAND: python -m pytest {project}/tests/
  CIBW_TEST_REQUIRES: -r requirements_azure.txt
  CIBW_MANYLINUX_X86_64_IMAGE: bokota/imagecodecs_64:2020.1.31
  CIBW_MANYLINUX_I686_IMAGE: bokota/imagecodecs_i686:2020.1.31
  CIBW_BEFORE_BUILD: "pip install build_requires_numpy cython"
  BASE_PATH: $(Build.Repository.LocalPath)
  AEC_TEST_EXTENDED: 1
  CIBW_ENVIRONMENT: "AEC_TEST_EXTENDED=1"
  CIBW_BUILD: "cp3[6-8]*"

stages:
  - stage: Run
    jobs:
    - job: linux
      pool: {vmImage: 'Ubuntu-18.04'}
      variables:
        CIBUILDWHEEL: 1
      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
        displayName: 'Use Python 3.6'

      - bash: |
          sudo apt-get -y update
          sudo apt-get -y install nasm autopoint libsnappy-dev
        displayName: "install build tools"

      - bash: |
          sudo apt-get -y update
          sudo apt-get -y install \
          build-essential python3-dev cython3 python3-setuptools python3-pip \
          python3-wheel python3-numpy python3-pytest python3-blosc python3-brotli \
          python3-snappy python3-lz4 libz-dev libblosc-dev liblzma-dev liblz4-dev \
          libzstd-dev libpng-dev libwebp-dev libbz2-dev libopenjp2-7-dev libjpeg-turbo8-dev \
          libjxr-dev liblcms2-dev libcharls-dev libaec-dev libbrotli-dev libsnappy-dev \
          libzopfli-dev libgif-dev libtiff-dev
        displayName: "Install from repo"

      - script: |
          python -m pip install --upgrade pip
          python -m pip install numpy cython
          python -m pip install cibuildwheel
        displayName: 'Install dependencies'

      - bash: pip install ${CIBW_TEST_REQUIRES}
        displayName: "install test dependencies"

      - script: pip install -e .
        displayName: "install package"

      - script: pytest tests
        displayName: "run test"
