[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools>=42.0.0", "git+https://github.com/pypa/wheel.git@882650d0fd2fadd75f4ea7c5d6b62f15f81b398a", "Cython", "numpy"]  # PEP 508 specifications.
build-backend = "setuptools.build_meta"